name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-workflow-passing-data:
    uses: CommonWealthRobotics/Bowler-Script-Release-CI/.github/workflows/reusable-release.yml@feature/linksource
    with:
      filename: "Hephaestus-Arm-Manufacturing-Files"
      filelocation: "./hephaestus.xml"   
